//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryToolEntities : DbContext
    {
        public InventoryToolEntities()
            : base("name=InventoryToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item_Consumption> Item_Consumption { get; set; }
        public virtual DbSet<Lk_Category> Lk_Category { get; set; }
        public virtual DbSet<Lk_Color> Lk_Color { get; set; }
        public virtual DbSet<LK_Material> LK_Material { get; set; }
        public virtual DbSet<LK_Outsource_Type> LK_Outsource_Type { get; set; }
        public virtual DbSet<LK_Part_Type> LK_Part_Type { get; set; }
        public virtual DbSet<LK_Unit> LK_Unit { get; set; }
        public virtual DbSet<M_Machine> M_Machine { get; set; }
        public virtual DbSet<M_Part> M_Part { get; set; }
        public virtual DbSet<M_Part_Type> M_Part_Type { get; set; }
        public virtual DbSet<M_Process> M_Process { get; set; }
        public virtual DbSet<M_Product> M_Product { get; set; }
        public virtual DbSet<M_PURCHASES_ORDER> M_PURCHASES_ORDER { get; set; }
        public virtual DbSet<M_PURCHASES_ORDER_DETAIL> M_PURCHASES_ORDER_DETAIL { get; set; }
        public virtual DbSet<M_Role> M_Role { get; set; }
        public virtual DbSet<M_User> M_User { get; set; }
        public virtual DbSet<M_Window> M_Window { get; set; }
        public virtual DbSet<Machine_Process> Machine_Process { get; set; }
        public virtual DbSet<Part_Manufacturing_Step> Part_Manufacturing_Step { get; set; }
        public virtual DbSet<Product_Part> Product_Part { get; set; }
        public virtual DbSet<Row_Material_Item> Row_Material_Item { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Window_Role_Permission> Window_Role_Permission { get; set; }
        public virtual DbSet<M_Branch> M_Branch { get; set; }
        public virtual DbSet<M_Company> M_Company { get; set; }
    }
}
