//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Consumption
    {
        public int Item_Consumption_Id { get; set; }
        public Nullable<int> Row_Material_Item_Id { get; set; }
        public Nullable<int> Machine_Process_Id { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Machine_Process Machine_Process { get; set; }
        public virtual Row_Material_Item Row_Material_Item { get; set; }
    }
}
