//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Branch
    {
        public int Branch_id { get; set; }
        public string tin_no { get; set; }
        public string Branch_name { get; set; }
        public string address1 { get; set; }
        public string pan_no { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string Fax_No { get; set; }
        public Nullable<int> is_active { get; set; }
        public string future1 { get; set; }
        public string future2 { get; set; }
        public string delivery_at { get; set; }
    }
}
