//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Part()
        {
            this.Part_Manufacturing_Step = new HashSet<Part_Manufacturing_Step>();
            this.Part_Manufacturing_Step1 = new HashSet<Part_Manufacturing_Step>();
            this.Product_Part = new HashSet<Product_Part>();
        }
    
        public int Part_Id { get; set; }
        public Nullable<int> Part_Type_Id { get; set; }
        public Nullable<int> Outsource_Type_Id { get; set; }
        public string Part_Code { get; set; }
        public string Part_Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Color_Id { get; set; }
        public Nullable<int> Material_Id { get; set; }
    
        public virtual Lk_Category Lk_Category { get; set; }
        public virtual Lk_Color Lk_Color { get; set; }
        public virtual LK_Material LK_Material { get; set; }
        public virtual LK_Outsource_Type LK_Outsource_Type { get; set; }
        public virtual M_Part_Type M_Part_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part_Manufacturing_Step> Part_Manufacturing_Step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part_Manufacturing_Step> Part_Manufacturing_Step1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Part> Product_Part { get; set; }
    }
}
