//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PURCHASES_ORDER_DETAIL
    {
        public int Purchase_Order_Detail_Id { get; set; }
        public Nullable<int> Purchases_Order_Id { get; set; }
        public Nullable<int> Row_Material_Item_Id { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Item_Rate { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string future1 { get; set; }
        public string future2 { get; set; }
    
        public virtual M_PURCHASES_ORDER M_PURCHASES_ORDER { get; set; }
        public virtual Row_Material_Item Row_Material_Item { get; set; }
    }
}
