//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PURCHASES_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_PURCHASES_ORDER()
        {
            this.M_PURCHASES_ORDER_DETAIL = new HashSet<M_PURCHASES_ORDER_DETAIL>();
        }
    
        public int Purchases_Order_Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Purchases_Order_No { get; set; }
        public string Future1 { get; set; }
        public string Future2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PURCHASES_ORDER_DETAIL> M_PURCHASES_ORDER_DETAIL { get; set; }
    }
}
