//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_Process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machine_Process()
        {
            this.Item_Consumption = new HashSet<Item_Consumption>();
        }
    
        public int Machine_Process_Id { get; set; }
        public Nullable<int> Machine_Id { get; set; }
        public Nullable<int> Process_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Consumption> Item_Consumption { get; set; }
        public virtual M_Machine M_Machine { get; set; }
        public virtual M_Process M_Process { get; set; }
    }
}
