//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_Manufacturing_Step
    {
        public int Part_Manufacturing_Step_Id { get; set; }
        public Nullable<int> Part_Id { get; set; }
        public Nullable<int> Process_Id { get; set; }
        public Nullable<int> Output_Part_Id { get; set; }
        public Nullable<int> Step_Sequence { get; set; }
    
        public virtual M_Part M_Part { get; set; }
        public virtual M_Part M_Part1 { get; set; }
        public virtual M_Process M_Process { get; set; }
    }
}
