//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Part
    {
        public int Product_Part_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Part_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual M_Part M_Part { get; set; }
        public virtual M_Product M_Product { get; set; }
    }
}
