//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Row_Material_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Row_Material_Item()
        {
            this.Item_Consumption = new HashSet<Item_Consumption>();
            this.M_PURCHASES_ORDER_DETAIL = new HashSet<M_PURCHASES_ORDER_DETAIL>();
        }
    
        public int Row_Material_Item_Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Color_Id { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> Material_Id { get; set; }
        public string Dimension { get; set; }
        public string Brand_Name { get; set; }
        public string Item_Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Consumption> Item_Consumption { get; set; }
        public virtual Lk_Category Lk_Category { get; set; }
        public virtual Lk_Color Lk_Color { get; set; }
        public virtual LK_Material LK_Material { get; set; }
        public virtual LK_Unit LK_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PURCHASES_ORDER_DETAIL> M_PURCHASES_ORDER_DETAIL { get; set; }
    }
}
