//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Window_Role_Permission
    {
        public int Window_Id { get; set; }
        public int Role_Id { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanAdd { get; set; }
        public Nullable<bool> CanUpdate { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanPrint { get; set; }
        public Nullable<bool> CanDownload { get; set; }
        public Nullable<bool> CanUpload { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedUTCDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedUTCDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual M_Role M_Role { get; set; }
        public virtual M_Window M_Window { get; set; }
    }
}
