//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryTool.UI.UserMessage", typeof(UserMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file is empty.
        /// </summary>
        internal static string fileEmpty {
            get {
                return ResourceManager.GetString("fileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        internal static string fileUpload {
            get {
                return ResourceManager.GetString("fileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to do undo of last submitted approval request.
        /// </summary>
        internal static string lastActionFail {
            get {
                return ResourceManager.GetString("lastActionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last submitted request approval is successfully reverted back.
        /// </summary>
        internal static string lastActionSuccess {
            get {
                return ResourceManager.GetString("lastActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record(s) Deleted Successfully.
        /// </summary>
        internal static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recode can not deleted.
        /// </summary>
        internal static string msgDeletePrevent {
            get {
                return ResourceManager.GetString("msgDeletePrevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is already present in the system. Please select a different value..
        /// </summary>
        internal static string msgDuplicate {
            get {
                return ResourceManager.GetString("msgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This status order is already present in the system. Please select a different status order.
        /// </summary>
        internal static string msgDuplicateStep {
            get {
                return ResourceManager.GetString("msgDuplicateStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record(s) Inserted Successfully.
        /// </summary>
        internal static string msgInsert {
            get {
                return ResourceManager.GetString("msgInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record(s) Updated Successfully.
        /// </summary>
        internal static string msgUpdate {
            get {
                return ResourceManager.GetString("msgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recode can not Update.
        /// </summary>
        internal static string msgUpdatePrevent {
            get {
                return ResourceManager.GetString("msgUpdatePrevent", resourceCulture);
            }
        }
    }
}
