//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDGBudgetTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_Approval_Stage1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LK_Approval_Stage1()
        {
            this.ApprovalStage_ApprovalStatus = new HashSet<ApprovalStage_ApprovalStatus>();
            this.BudgetRequests = new HashSet<BudgetRequest>();
            this.Role_ApprovalStage = new HashSet<Role_ApprovalStage>();
        }
    
        public int Approval_Stage_Id { get; set; }
        public string Approval_Stage_Name { get; set; }
        public Nullable<int> Status_Order { get; set; }
        public Nullable<bool> IsBudgetRequestLocked { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedUTCDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedUTCDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalStage_ApprovalStatus> ApprovalStage_ApprovalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetRequest> BudgetRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role_ApprovalStage> Role_ApprovalStage { get; set; }
    }
}
