//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Part
    {
        public int Part_Id { get; set; }
        public Nullable<int> Part_Type_Id { get; set; }
        public Nullable<int> Outsource_Type_Id { get; set; }
        public string Part_Code { get; set; }
        public string Part_Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Color_Id { get; set; }
        public Nullable<int> Material_Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedUTCDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedUTCDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Unit_Id { get; set; }
    }
}
