//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Supplier
    {
        public int Supplier_Id { get; set; }
        public string Supplier_Code { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<int> Manufacturing_Days { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedUTCDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedUTCDate { get; set; }
        public bool IsActive { get; set; }
    }
}
